### ISSUE TITLE
loading db

### ISSUE THREAD

**Issue by ilker18880** [AliAkhgar/RandstormBTC#1]
Didnt load the btah.txt when running the script and no error

**Comment by ilker18880** [comment]
instead of loading with the code i use bash to load file like this
cat btah.txt | awk '{print "SET "$1" 1"}' | redis-cli --pipe
and run script is this ok?

**Comment by AliAkhgar** [comment]
> instead of loading with the code i use bash to load file like this cat btah.txt | awk '{print "SET "$1" 1"}' | redis-cli --pipe and run script is this ok?

this repo is completely educational and will not generate you successful wallets.
btah.txt is the btc wallet addresses which are downloaded from internet. its loaded into redis when the condition boolean is TRUE. and will be checked against.
THIS REPO WILL NOT HELP YOU GET WALLETS.
